// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    firebase: {
      apiKey: 'AIzaSyDx29_iAIE1hA4DZxwxLE48qY3jEpZaPlQ',
      authDomain: 'jp-ingreso-egreso-app.firebaseapp.com',
      projectId: 'jp-ingreso-egreso-app',
      storageBucket: 'jp-ingreso-egreso-app.appspot.com',
      messagingSenderId: '78881976602',
      appId: '1:78881976602:web:92511143d11416e3083ca3',
      measurementId: 'G-10P8M9X1V1',
      databaseURL: '<your-database-URL>'
    }
  };